### ISSUE TITLE
_initWithId(id: Int) returns data, with some offset

### ISSUE THREAD

**Issue by amiralishah** [remirobert/Camembert#17]
I have a model name Ingredient having name, brand, cost
When I _initWithId some ingredient the object that I get is of type "Ingredient" but it's properties are not returned in the correct way. i.e. when I access .name it returns empty, but when access .brand it returns the name and on .cost it returns the brand.. simple it does the following 

.name = ""
.brand = .name
.cost = .brand
.cost = (Only God knows)

Does anybody understand this error? Can anyone please help me with it, I have tried to make a breakpoint in CamembertModel.swift and try to track down the error but no luck..

**Comment by RayanSaeed** [comment]
I faced the same issue, and fixed it by making some changes to the Camembert source files, I'll make a pull request for that soon.
