### ISSUE TITLE
Issue in getting class name

### ISSUE THREAD

**Issue by OmarBizreh** [remirobert/Camembert#7]
Hi, I faced an issue in this function: 
it is always returning nil when project name includes spaces, for example if my project is called "My App" the return result will be nil. If I know Objective-C I would have helped fixing it :+1: 
```Swift
id camembertCreateObject(NSString *nameClass) {
    NSString *appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];
    NSString *classStringName = [NSString stringWithFormat:@"_TtC%lu%@%lu%@", (unsigned long)appName.length,
                                 appName, (unsigned long)nameClass.length, nameClass];
    
    Class customClass = NSClassFromString(classStringName);
    if (customClass == nil) {
        return nil;
    }
    return [[customClass alloc] init];
}
```

**Comment by remirobert** [comment]
Hi, it will be no fix for this issue. In fact i allergy noticed it. And i never found any way to fix it.

**Comment by OmarBizreh** [comment]
To think of it, no one should create a project with spaces in its name, Visual Studio does make issues when a solution has spaces in its name, I should have expected the same for Apple.
Sorry for the false alarm.
