### ISSUE TITLE
Is "initDataBase(nameDatabase :String)" method working?

### ISSUE THREAD

**Issue by bradex** [remirobert/Camembert#8]
I got an "unexpectedly found nil while unwrapping an Optional value" error at "DataAccess.access.DbPath get".
"initDataBase(databaseFolder: String, nameDatabase :String)" is working, though.

**Comment by remirobert** [comment]
ok thanks, i will check it

**Comment by OmarBizreh** [comment]
Hi, I just merged a new commit to fix the issue, @bradex can you please download the files again and try.

**Comment by remirobert** [comment]
I tried, and it works with wrong path or nil value. Thanks for you commit again.

**Comment by OmarBizreh** [comment]
Your welcome sorry for causing the issue. I hope @bradex got things working now :)

**Comment by bradex** [comment]
:+1:
